export enum ECreateGame {
	RESULT_CREATE_GAME = 'RESULT_CREATE_GAME',
	JOIN_GAME = 'JOIN_GAME',
	CREATE_GAME = 'CREATE_GAME',
	RESTART_GAME = 'RESTART_GAME',
	ERROR_CREATE_GAME = 'ERROR_CREATE_GAME',
}
